#!/bin/bash
# This file should not be modified -- make local changes to
# /etc/ppp/ip-down.local instead

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

LOGDEVICE=$6
REALDEVICE=$1
NETWORKDIR=/etc/sysconfig/network-scripts

[ -x /etc/ppp/ip-down.local ] && /etc/ppp/ip-down.local "$@"

# get Nickname name of device
[ -f /etc/ppp/$LOGDEVICE ] && . /etc/ppp/$LOGDEVICE
[ -f $NETWORKDIR/${NICKNAME} ] && $NETWORKDIR/ifdown-post ${NICKNAME}

exit 0
