#!/bin/bash
# This file should not be modified -- make local changes to
# /etc/ppp/ip-up.local instead

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

LOGDEVICE=$6
REALDEVICE=$1
NETWORKDIR=/etc/sysconfig/network-scripts

# get Alias name of device
[ -f /etc/ppp/$LOGDEVICE ] && . /etc/ppp/$LOGDEVICE

[ -f $NETWORKDIR/${NICKNAME} ] && $NETWORKDIR/ifup-post ${NICKNAME}

[ -x /etc/ppp/ip-up.local ] && /etc/ppp/ip-up.local "$@"

exit 0
