#!/bin/bash

# This file should not be modified -- make local changes to
# /etc/ppp/ip-up.local instead

LOGDEVICE=$6
REALDEVICE=$1

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

[ -x /etc/ppp/ip-up.local ] && /etc/ppp/ip-up.local $*

# Used for clustering heartbeat monitoring stuff.
[ -x /etc/ppp/ip-up.heart ] && /etc/ppp/ip-up.heart $*

/etc/sysconfig/network-scripts/ifup-post ifcfg-${LOGDEVICE}

exit 0
