#!/bin/bash

# This file should not be modified -- make local changes to
# /etc/ppp/ipv6-up.local instead

# Version: 2002-01-12

LOGDEVICE=$6
REALDEVICE=$1

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

# Setup IPv6
if [ -f /etc/sysconfig/network ]; then
	. /etc/sysconfig/network
	
	if [ "${NETWORKING_IPV6}" = "yes" -a -x /etc/sysconfig/network-scripts/ifup-ipv6 ]; then
		# Source IPv4 helper functions
		cd /etc/sysconfig/network-scripts
		. network-functions

		# Source IPv6 helper functions
		. /etc/sysconfig/network-scripts/network-functions-ipv6

		CONFIG=$1
		[ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
		source_config

		/etc/sysconfig/network-scripts/ifup-ipv6 $REALDEVICE

		if [ "$IPV6_CONTROL_RADVD" = "yes" ]; then
			# Control running radvd
			ipv6_trigger_radvd up "$IPV6_RADVD_TRIGGER_ACTION" $IPV6_RADVD_PIDFILE
		fi
        fi
fi

[ -x /etc/ppp/ipv6-up.local ] && /etc/ppp/ipv6-up.local "$@"

exit 0
