#!/bin/bash
# This file should not be modified -- make local changes to
# /etc/ppp/ipv6-up.local instead

# Version: 2002-10-30

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

LOGDEVICE=$6
REALDEVICE=$1

[ -x /etc/sysconfig/network-scripts/ifup-ipv6 ] || exit 0
[ -f /etc/sysconfig/network ] || exit 0
. /etc/sysconfig/network
[ "${NETWORKING_IPV6}" = "yes" ] || exit 0

cd /etc/sysconfig/network-scripts
. network-functions
. network-functions-ipv6

CONFIG=$1
[ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
source_config

/etc/sysconfig/network-scripts/ifup-ipv6 $REALDEVICE

if [ "$IPV6_CONTROL_RADVD" = "yes" ]; then
	# Control running radvd
	ipv6_trigger_radvd up "$IPV6_RADVD_TRIGGER_ACTION" $IPV6_RADVD_PIDFILE
fi

[ -x /etc/ppp/ipv6-up.local ] && /etc/ppp/ipv6-up.local "$@"

exit 0
