#!/bin/bash

# Version: 2002-01-12

# This file should not be modified -- make local changes to
# /etc/ppp/ipv6-down.local instead

LOGDEVICE=$6
REALDEVICE=$1

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

[ -x /etc/ppp/ipv6-up.local ] && /etc/ppp/ipv6-up.local "$@"

# Setup IP6
if [ -f /etc/sysconfig/network ]; then
	. /etc/sysconfig/network
	
	if [ "${NETWORKING_IPV6}" = "yes" -a -x /etc/sysconfig/network-scripts/ifdown-ipv6 ]; then
		# Source IPv4 helper functions
		cd /etc/sysconfig/network-scripts
		. network-functions

		# Source IPv6 helper functions
		. /etc/sysconfig/network-scripts/network-functions-ipv6

		CONFIG=$1
		[ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
		source_config

		/etc/sysconfig/network-scripts/ifdown-ipv6 $REALDEVICE

		if [ "$IPV6_CONTROL_RADVD" = "yes" ]; then
			# Control running radvd
			ipv6_trigger_radvd down "$IPV6_RADVD_TRIGGER_ACTION" $IPV6_RADVD_PIDFILE
		fi
	fi
fi

exit 0
