#!/bin/sh

export LC_ALL=C

if [ "$2" = "down" ]; then
	ip route ls | grep -q ^default || {
		[ -f /var/lock/subsys/netfs ] && /etc/rc.d/init.d/netfs stop
	}
fi

if [ "$2" = "up" ]; then
	defdev=$(ip route ls | awk '/^default/ { print $NF }')
	if [ "$defdev" = "$1" ]; then
		/sbin/chkconfig netfs && /etc/rc.d/init.d/netfs start
	fi
fi

