# doc: https://packit.dev/docs/
---

specfile_path: ./initscripts.spec

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - centos-stream-9-x86_64

  - job: copr_build
    trigger: release
    metadata:
      targets:
        - centos-stream-9-x86_64
