specfile_path: initscripts.spec
synced_files:
- initscripts.spec
- .packit.yaml

upstream_project_name: initscripts
downstream_package_name: initscripts

allowed_gpg_keys:
- 4AEE18F83AFDEB23      # GitHub

jobs:
- job: sync_from_downstream
  trigger: commit
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: master
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: f30
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
        - fedora-rawhide-x86_64
        - fedora-30-x86_64
