# doc: https://packit.dev/docs/
---

specfile_path: ./initscripts.spec

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide-x86_64
      - centos-stream-8-x86_64
      - centos-stream-9-x86_64

  - <<: *copr
    trigger: release
