# doc: https://packit.dev/docs/
# config: https://packit.dev/docs/configuration/
---

specfile_path: initscripts.spec

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - centos-stream-8-x86_64
      - centos-stream-9-x86_64

  - <<: *copr
    trigger: commit
    branch: main
