#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin

# We need to source this so that the login screens get translated
. /etc/profile.d/lang.sh

# Run preferred X display manager
preferred=
if [ -f /etc/sysconfig/desktop ]; then
	if grep -q GNOME /etc/sysconfig/desktop 2>/dev/null; then
		preferred=gdm
	elif grep -q KDE /etc/sysconfig/desktop 2> /dev/null; then
		preferred=kdm
	elif grep -q AnotherLevel /etc/sysconfig/desktop 2> /dev/null; then
                preferred=xdm
	fi
fi
if [ -z "$preferred" ]; then
	if which gdm >/dev/null 2>&1; then
		preferred=gdm
	elif which kdm >/dev/null 2>&1; then
		preferred=kdm
	elif which xdm >/dev/null 2>&1; then
		preferred=xdm
	fi
fi
if [ -n "$preferred" ] && which $preferred >/dev/null 2>&1; then 
	exec `which $preferred` $*
fi
exit 1								
