#!/bin/sh

if [ -z "$1" ]; then
	echo "no service specified" >&2
	exit 1
elif [ -x "/etc/rc.d/init.d/$1" ]; then
	service=$1
	shift
	"/etc/rc.d/init.d/$service" $*
else
	echo "$1: unrecognized service" >&2
	exit 1
fi
