#!/bin/sh

PATH=/bin:/usr/bin

if [ -f /etc/sysconfig/i18n ]; then
  . /etc/sysconfig/i18n
fi

if [ -x /bin/consolechars -o -x /usr/bin/consolechars ]; then
  if [ -n "$SYSFONT" ]; then
    ARGS=$SYSFONT
    if [ -n "$UNIMAP" ]; then
       ARGS="$ARGS --sfm $UNIMAP"
    fi
    if [ -n "$SYSFONTACM" ]; then
       ARGS="$ARGS --acm $SYSFONTACM"
    fi
    consolechars -f $ARGS
  fi
elif [ -x /usr/bin/setfont ]; then
  if [ -n "$SYSFONT" -a -n "$UNIMAP" ]; then
    /usr/bin/setfont $SYSFONT -u $UNIMAP
  elif [ -n "$SYSFONT" ]; then
    /usr/bin/setfont $SYSFONT
#  else
#    /usr/bin/setfont
  fi
else
  echo "can't set font"
  exit 1
fi
exit 0
