.TH  SYS-UNCONFIG 8 "Wed Jul 28 1999"
.SH NAME
sys-unconfig \- shell script to reconfigure the system upon next boot
.SH SYNOPSIS
\fBsys-unconfig\fR
.SH DESCRIPTION
\fBsys-unconfig\fR provides a simple method of reconfiguring a system
in a new environment. Upon executing sys-unconfig will poweroff your
system, and run firstboot at next boot.

.SH FILES
.PD 0
.TP 20
\fI/.unconfigured\fR
The presence of this file will trigger firsboot.

.SH NOTES
.PD
This utility should not be used for creating cloud or virtual machine images.
For that use please see \fBvirt-sysprep\fP.

.PD
.SH "SEE ALSO"
.BR virt-sysprep(1)

.SH AUTHORS
.nf
H.J. Lu <hjl@valinux.com>
.fi
