.TH  SYS-UNCONFIG 8 "Wed Jul 28 1999"
.SH NAME
sys-unconfig \- shell script to reconfigure the system upon next boot
.SH SYNOPSIS
\fBsys-unconfig\fR
.SH DESCRIPTION
\fBsys-unconfig\fR provides a simple method of reconfiguring a system
in a new enviroment.  Upon executing sys-unconfig will halt your
system, and run the following configuration programs at boot:
passwd (to change the root password), netconfig, timeconfig,
authconfig, and ntsysv.

.SH FILES
.PD 0
.TP 20
\fI/.unconfigured\fR
The presence of this file will cause /etc/rc.d/rc.sysinit to run
the programs mentioned above.

.PD
.SH "SEE ALSO"
.BR passwd (1),
.BR netconfig (8),
.BR timeconfig (8),
.BR authconfig (8),
.BR ntsysv(8)

.SH AUTHORS
.nf
H.J. Lu <hjl@valinux.com>
.fi
