#!/bin/sh

cd /etc/sysconfig/network-scripts || exit 1
. ./network-functions

# shellcheck disable=SC2034
CONFIG=$1
source_config

if [ "foo$2" = "fooboot" ] && is_false "${ONBOOT}"; then
    exit
fi

[ -z "$PREFIX" ] && eval "$(/bin/ipcalc --prefix ${IPADDR} ${NETMASK})"
ip addr add ${IPADDR} peer ${REMIP}/${PREFIX} dev ${DEVICE}
set_link_up ${DEVICE}
ip route add ${NETWORK} dev ${DEVICE}

. /etc/sysconfig/network

if [ "${GATEWAY}" != "" ]; then
    if [ "${GATEWAYDEV}" = "" ] || [ "${GATEWAYDEV}" = "${DEVICE}" ]; then
        # set up default gateway
        ip route replace default ${METRIC:+metric $METRIC} via ${GATEWAY}
    fi
fi

/etc/sysconfig/network-scripts/ifup-post $1
