#!/bin/sh
#
# /etc/sysconfig/network-scripts/ifup-plusb
#
# the plusb network driver is a USB host-host cable based on the Prolific
# chip. It works a lot like the plip driver.  
#
# To get the plusb module to load automatically at boot, you will need to
# add the following lines to /etc/conf.modules:
#
# alias plusb0 plusb
#

cd /etc/sysconfig/network-scripts || exit 1
. ./network-functions

# shellcheck disable=SC2034
CONFIG=$1
source_config

if [ "foo$2" = "fooboot" ] && is_false "${ONBOOT}" = "no"; then
    exit
fi

[ -z "$PREFIX" ] && eval "$(/bin/ipcalc --prefix ${IPADDR} ${NETMASK})"

if [ ${BROADCAST} != ""  ]  ; then
    ip addr add ${IPADDR} peer ${REMIP}/${PREFIX} broadcast ${BROADCAST} dev ${DEVICE}
else
    ip addr add ${IPADDR} peer ${REMIP}/${PREFIX} dev ${DEVICE}
fi
set_link_up ${DEVICE}

. /etc/sysconfig/network

if [ "${GATEWAY}" != "" ]; then
    if [ "${GATEWAYDEV}" = "" ] || [ "${GATEWAYDEV}" = "${DEVICE}" ]; then
        # set up default gateway
        ip route replace default ${METRIC:+metric $METRIC} via ${GATEWAY}
    fi
fi

/etc/sysconfig/network-scripts/ifup-post $1
