#!/bin/bash
#
# Configure machine if necessary.

. /etc/init.d/functions

if [ -x /usr/bin/plymouth ]; then
    /usr/bin/plymouth quit
fi
   
if [ -x /usr/sbin/firstboot ]; then
    /usr/sbin/firstboot
fi

# Reread in network configuration data.
if [ -f /etc/sysconfig/network ]; then
    . /etc/sysconfig/network

    # Reset the hostname.
    action $"Resetting hostname ${HOSTNAME}: " hostname ${HOSTNAME}
fi
