#!/bin/bash
#
# Configure machine if necessary.

. /etc/init.d/functions

if [ -x /usr/bin/rhgb-client ] && /usr/bin/rhgb-client --ping ; then
    /usr/bin/rhgb-client --quit
fi
   
if [ -x /usr/sbin/firstboot ]; then
    /usr/sbin/firstboot
fi

# Reread in network configuration data.
if [ -f /etc/sysconfig/network ]; then
    . /etc/sysconfig/network

    # Reset the hostname.
    action $"Resetting hostname ${HOSTNAME}: " hostname ${HOSTNAME}
fi
