#!/bin/bash
#
# Configure machine if necessary.

. /etc/init.d/functions

if [ -x /bin/plymouth ]; then
    /bin/plymouth quit
fi
   
if [ -x /usr/sbin/firstboot ]; then
    /usr/sbin/firstboot
fi

# Reread in network configuration data.
if [ -r /etc/hostname ]; then
    HOSTNAME=$(cat /etc/hostname)
    # Reset the hostname.
    action $"Resetting hostname ${HOSTNAME}: " hostname ${HOSTNAME}
fi
