#!/bin/bash
PATH=/sbin:/usr/sbin:/bin:/usr/bin

cd /etc/sysconfig/network-scripts
. network-functions

CONFIG=$1
source_config

file=/var/run/pppwatch-$DEVICE.pid

if [ ! -f $file ]; then
    # ppp isn't running, or we didn't start it
    exit 0
fi

PID=`cat $file`
[ -n "$PID" ] || exit 1

kill -TERM $PID > /dev/null 2>&1
[ ! -d /proc/$PID ] && exit 0
sleep 2
[ ! -d /proc/$PID ] && exit 0

# killing ppp-watch twice in a row causes it to send a SIGKILL to pppd pgrp
kill -TERM $PID > /dev/null 2>&1
# ip-down won't run in this case
/etc/sysconfig/network-scripts/ifdown-post $1

exit 1
