#!/bin/bash

cd /etc/sysconfig/network-scripts
. network-functions

CONFIG=$1
source_config

# signals ifup-sl not to persist
rm -f /var/run/sl-$DEVICE.dev

PID=`pidof dip-$DEVICE`
#
# The proctitle for connected dip daemons is actually "-dip (ipaddr)"
#	with ipaddr == local on dial-out,  remote on dial-in
# Grab the PID of connected dial-out daemon.
#
if [ -z "$PID" ]; then
  PID=`pidof -- -dip\ \($IPADDR\)`
fi
if [ -z "$PID" ]; then
  exit 1
fi

kill $PID > /dev/null 2>&1
if [ ! -d /proc/$PID ]; then
  /etc/sysconfig/network-scripts/ifdown-post $1
  exit 0
fi
sleep 2
if [ ! -d /proc/$PID ]; then
  /etc/sysconfig/network-scripts/ifdown-post $1
  exit 0
fi

kill -KILL $PID > /dev/null 2>&1
if [ -d /proc/$PID ]; then
  logger -p daemon.info -t ifdown-ppp "ifdown-ppp unable to kill pppd-$DEVICE" &
else
  /etc/sysconfig/network-scripts/ifdown-post $1
fi
[ ! -d /proc/$PID ] && exit 0

exit 1

