#!/bin/sh
# This should be called whenever an interface goes down, not just when
# it is brought down explicitly.

cd /etc/sysconfig/network-scripts
. network-functions

CONFIG=$1
source_config

if [ "${DEVICETYPE}" = "ppp" -o "${DEVICETYPE}" = "ippp" ]; then
    if [ -f /etc/resolv.conf.save ]; then
	cat /etc/resolv.conf.save > /etc/resolv.conf
	rm -f /etc/resolv.conf.save
    fi
    if [ -f /etc/ppp/peers/$DEVICE ] ; then
	rm -f /etc/ppp/peers/$DEVICE
    fi
fi

# Reset the default route if this interface had a special one
if ! check_default_route ; then
    # ISDN device needs special handling dial on demand
    if [ "${DEVICETYPE}" = "ippp" -o "${DEVICETYPE}" = "isdn" ] && [ "$DIALMODE" = "auto" ] ; then
        if [ -z "$GATEWAY" ] ; then
            /sbin/ip route add default ${WINDOW:+window $WINDOW} dev ${DEVICE}
        else
            /sbin/ip route add default ${WINDOW:+window $WINDOW} via ${GATEWAY}
        fi
    else
        add_default_route ${DEVICE}
    fi
fi

# Notify programs that have requested notification
do_netreport

if [ -x /sbin/ifdown-local ]; then
    /sbin/ifdown-local ${DEVICE}
fi

exit 0
