#! /bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin 

CONFIG=$1

. $CONFIG

# stopping ibod daemon for channel bundling
if [ -f /var/lock/subsys/ibod ] ; then
    kill -9  $(pidof ibod) >/dev/null 2>&1
    rm -f /var/lock/subsys/ibod
fi

# shutdown isdn device
isdnctrl hangup $DEVICE >/dev/null 2>&1
sleep 1
ifconfig $DEVICE down >/dev/null 2>&1

# delete isdn device
isdnctrl delif $DEVICE >/dev/null 2>&1

# kill ipppd daemon
if [ -f /var/run/ipppd.$DEVICE.pid ] ; then
    pppdpid=`cat /var/run/ipppd.$DEVICE.pid`
    kill -9 $pppdpid > /dev/null 2>&1
    rm -f /var/run/ipppd.$DEVICE.pid > /dev/null 2>&1
fi
