#! /bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin 

# Get global network configuration
[ -f /etc/sysconfig/network ] && . /etc/sysconfig/network

CONFIG=$1

. ./$CONFIG

# stopping ibod daemon for channel bundling
if [ -f /var/lock/subsys/ibod ] ; then
    kill -9  $(pidof ibod) >/dev/null 2>&1
    rm -f /var/lock/subsys/ibod
fi

# Shut down IPv6
/etc/sysconfig/network-scripts/ifdown-ipv6 $CONFIG

# shutdown isdn device
isdnctrl hangup $DEVICE >/dev/null 2>&1
sleep 1
ip link set dev $DEVICE down >/dev/null 2>&1

# delete isdn device
isdnctrl delif $DEVICE >/dev/null 2>&1

# kill ipppd daemon
if [ -f /var/run/ipppd.$DEVICE.pid ] ; then
    pppdpid=$(cat /var/run/ipppd.$DEVICE.pid)
    kill -9 $pppdpid > /dev/null 2>&1
    rm -f /var/run/ipppd.$DEVICE.pid > /dev/null 2>&1
fi
