#!/bin/sh
#
# /etc/sysconfig/network-scripts/ifup-iucv
#
# the iucv network driver is a point-to-point driver on S/390 machines
#
# To get the iucv module to load automatically at boot, you will need to
# add the following line to /etc/modprobe.conf:
#
# alias iucv0 netiucv
#

. /etc/sysconfig/network

cd /etc/sysconfig/network-scripts
. network-functions
 
CONFIG=$1
[ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
source_config

if [ "$2" = "boot" -a "${ONBOOT}" = "no" ]
then
	exit
fi
[ -n "${MTU}" ] && opts="${opts} mtu ${MTU}"

echo "$PEERID" > /sys/bus/iucv/drivers/netiucv/connection 2>/dev/null

ifconfig ${DEVICE} ${IPADDR} ${opts} pointopoint ${GATEWAY} netmask ${NETMASK}
if [ "${NETWORK}" != "" ] ; then
	route add -host ${GATEWAY} metric 1 ${DEVICE}
fi


if [ "${GATEWAY}" != "" ]; then
	if [ "${GATEWAYDEV}" = "" -o "${GATEWAYDEV}" = "${DEVICE}" ]; then
		# set up default gateway
		route add default gw ${GATEWAY} ${METRIC:+metric $METRIC}
	fi
fi

/etc/sysconfig/network-scripts/ifup-post $1
