#!/bin/bash
#
# /etc/sysconfig/network-scripts/ifup-ctc
#
# the ctc network driver is a point-to-point driver on S/390 machines
#
# To get the ctc module to load automatically at boot, you will need to
# add the following line to /etc/modules.conf:
#
# alias ctc0 ctc
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

cd /etc/sysconfig/network-scripts
. network-functions

CONFIG=$1
[ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
source_config

if [ "$2" = "boot" -a "${ONBOOT}" = "no" ]
then
	exit
fi
[ -n "${MTU}" ] && opts="${opts} mtu ${MTU}"

ifconfig ${DEVICE} ${IPADDR} ${opts} pointopoint ${REMIP}

# Wait for the device to come up - the chandev'ified ctc driver can take
# quite a while...
timeout=0
while ! ping -w 30 -c ${REMIP} &>/dev/null; do
	timeout=$(($timeout + 1))
	if [ $timeout = 20 ]; then
		echo $"ERROR: ${DEVICE} did not come up!"
		break
	fi
done

if [ "${NETWORK}" != "" ] ; then
	route add -net ${NETWORK} netmask ${NETMASK} ${DEVICE}
fi

. /etc/sysconfig/network

if [ "${GATEWAY}" != "" ]; then
	if [ "${GATEWAYDEV}" = "" -o "${GATEWAYDEV}" = "${DEVICE}" ]; then
		# set up default gateway
		route add default gw ${GATEWAY}
	fi
fi

/etc/sysconfig/network-scripts/ifup-post $1
