#!/bin/bash
# configures IPX on $1 if appropriate

PATH=/sbin:/usr/sbin:/bin:/usr/bin

if [ "$1" = "" ]; then
	echo $"usage: $0 <net-device>"
	exit 1
fi

# cannot configure IPX with non-existant utilities
[ -x /sbin/ipx_interface ] || exit 0

. /etc/sysconfig/network

case $IPX in yes|true) ;; *) exit 0 ;; esac

cd /etc/sysconfig/network-scripts
. network-functions

CONFIG=$1
[ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
source_config

for frametype in 802.2 802.3 ETHERII SNAP ; do
    framename=$(echo $frametype | sed 's/\./_/')
    eval ACT=\$IPXACTIVE_$framename
    case $ACT in
	yes|true)
		eval PRIM=\$IPXPRIMARY_$framename
		case $PRIM in
		    yes|true) primary=-p ;;
		    *) primary= ;;
		esac
		eval NUM=\$IPXNETNUM_$framename
		/sbin/ipx_interface add $primary $1 $frametype $NUM
		;;
    esac
done

exit 0

