#!/bin/sh
#
# /etc/sysconfig/network-scripts/ifup-iucv
#
# the iucv network driver is a point-to-point driver on S/390 machines
#
# To get the iucv module to load automatically at boot, you will need to
# add the following line to /etc/modules.conf:
#
# alias iucv0 netiucv
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin
 
cd /etc/sysconfig/network-scripts
. network-functions
 
CONFIG=$1
[ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
source_config

if [ "$2" = "boot" -a "${ONBOOT}" = "no" ]
then
	exit
fi
[ -n "${MTU}" ] && opts="${opts} mtu ${MTU}"

ifconfig ${DEVICE} ${IPADDR} ${opts} pointopoint ${REMIP}
if [ "${NETWORK}" != "" ] ; then
	route add -net ${NETWORK} netmask ${NETMASK} ${DEVICE}
fi

# this is broken! it's only here to keep compatibility with old RH sytstems
if [ "${GATEWAY}" != "" -a "${GATEWAY}" != "none" ]
then
	route add default gw ${GATEWAY} metric 1 ${DEVICE}
fi

. /etc/sysconfig/network

if [ "${GATEWAY}" != "" ]; then
	if [ "${GATEWAYDEV}" = "" -o "${GATEWAYDEV}" = "${DEVICE}" ]; then
		# set up default gateway
		route add default gw ${GATEWAY}
	fi
fi

/etc/sysconfig/network-scripts/ifup-post $1
