#! /bin/bash
#
# adds static routes which go through device $1
if [ -z "$1" ]; then
    echo $"usage: ifup-routes <net-device> [<nickname>]"
    exit 1
fi

handle_file () {
    . $1
    routenum=0
    while [ "x$(eval echo '$'ADDRESS$routenum)x" != "xx" ]; do
	eval `ipcalc -p $(eval echo '$'ADDRESS$routenum) $(eval echo '$'NETMASK$routenum)`
	line="$(eval echo '$'ADDRESS$routenum)/$PREFIX"
	if [ "x$(eval echo '$'GATEWAY$routenum)x" != "xx" ]; then
	    line="$line via $(eval echo '$'GATEWAY$routenum)"
	fi
	line="$line dev $2"
	/sbin/ip route add $line
	routenum=$(($routenum+1))
    done
}

FILES="/etc/sysconfig/network-scripts/route-$1"
if [ -n "$2" -a "$2" != "$1" ]; then
    FILES="$FILES /etc/sysconfig/network-scripts/route-$2"
fi

for file in $FILES; do
   if [ -f "$file" ]; then
       if egrep -q 'ADDRESS[0-9]+=' $file ; then
           # new format
	   handle_file $file $1
       else
           # older format
           while read line; do
               /sbin/ip route add $line
           done < "$file"
       fi
   fi
done


# Red Hat network configuration format
NICK=${2:-$1}
CONFIG="/etc/sysconfig/network-scripts/$NICK.route"
[ -f $CONFIG ] && handle_file $CONFIG $1
