#!/bin/sh

cd /etc/sysconfig/network-scripts

CONFIG=$1
. network-functions

need_hostname
source_config

DEVICETYPE=`echo $DEVICE | sed "s/[0-9]*$//"`
REALDEVICE=`echo $DEVICE | sed 's/:.*//g'`
if echo $DEVICE | grep -q ':' ; then
    ISALIAS=yes
else
    ISALIAS=no
fi

/etc/sysconfig/network-scripts/ifup-routes ${DEVICE}

if [ "$ISALIAS" = no ] ; then
    allow_null_glob_expansion=foo
    for alias in /etc/sysconfig/network-scripts/ifcfg-${DEVICE}:* ; do
	/etc/sysconfig/network-scripts/ifup $alias
    done
    unset allow_null_glob_expansion
fi

if [ -n "$NEEDHOSTNAME" -a ${DEVICE} != lo ]; then
    IPADDR=`ifconfig ${DEVICE} | grep 'inet addr' | 
	    awk -F: '{ print $2 } ' | awk '{ print $1 }'`
    eval `/sbin/ipcalc --silent --hostname ${IPADDR}` && set_hostname $HOSTNAME
fi

# Notify programs that have requested notification
do_netreport

exit 0
