#!/bin/sh
#
#
# rc.single     This file is executed by init when it goes into runlevel
#               1, which is the administrative state. It kills all
#               deamons and then puts the system into single user mode.
#               Note that the file systems are kept mounted.
#
# Author:       Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#               Modified for RHS Linux by Damien Neil
#

. /etc/rc.d/init.d/functions

# Set the path.
PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ "$1" != "start" ] ; then
   exit 0
fi

# Kill all processes.
[ "${BASH+bash}" = bash ] && enable kill

echo "Sending all processes the TERM signal..."
kill -15 -1
sleep 5
echo "Sending all processes the KILL signal.."
kill -9 -1

rm -f /var/lock/subsys/*

# this looks nices
[ -x /usr/bin/clear ] && /usr/bin/clear

# make sure modprobe is working
if [ -f /proc/sys/kernel/modprobe ]; then
   sysctl -w kernel.modprobe="/sbin/modprobe" >/dev/null 2>&1
fi

# If they want to run something in single user mode, might as well run it...
for i in /etc/rc.d/rc1.d/S[0-9][0-9]*; do
        # Check if the script is there.
        [ ! -f $i ] && continue
		
	# Don't run [KS]??foo.{rpmsave,rpmorig} scripts
	[ "${i%.rpmsave}" != "${i}" ] && continue
	[ "${i%.rpmorig}" != "${i}" ] && continue
	[ "${i%.rpmnew}" != "${i}" ] && continue
	[ "$i" = "/etc/rc.d/rc1.d/S00single" ] && continue
	$i start
done						

# Now go to the single user level.
echo "Telling INIT to go to single user mode."
exec init -t1 S
