#!/usr/bin/python

# xgettext_sh -- extracts translatable strings from a shell script
# Copyright (C) 1999 Conectiva Consultoria e Desenvolvimento de Sistemas LTDA
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

from sys import path
if not '/usr/lib/conectiva/xgettext_sh' in path:
    path[:0] = ['/usr/lib/conectiva/xgettext_sh']

from xgettext_sh import main

if __name__ == '__main__':
	main()
