.TH DOEXEC 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH NAME
doexec \- run an executable with an arbitrary argv[0]
.SH SYNOPSIS
.B doexec
\fI/path/to/executable\fP \fIargv[0]\fP [\fIargv[1-n]\fP]
.SH DESCRIPTION
.B doexec
simply runs the executable with the argv list provided.  It allows you
to specify an argv[0] other than the name of the executable.
.SH OPTIONS
All options are passed in the argv list to the executable being run.
