.TH initlog 8 "Sun Jan 24 1999"
.SH NAME
initlog \- log messages and events to the system logger
.SH SYNOPSIS
.B initlog
[\-cefnpqrs] [\-\-cmd=ARG] [\-\-event=ARG] [\-\-facility=ARG]
[\-\-name=ARG] [\-\-priority=ARG] [\-\-run=ARG] [\-\-string=ARG]
.SH DESCRIPTION
\fBinitlog\fR logs messages and events to the system logger.
It is mainly designed for use in init scripts. initlog
reads a configuration file
.I /etc/initlog.conf
by default, to determine its settings. Any line preceded with a 
.I #
is a comment, and the following configuration directives
are recognized:
.TP
.I facility <logging facility>
Sets the default logging facility
.TP
.I priority <logging priority>
Sets the default logging priority
.TP
.I ignore <regexp>
Messages that match the regular expression will not be logged.
.TP
initlog behavior can also be configured by command-line options.

\fBNote that initlog is deprecated and will be removed in a future
release.\fR

.SS OPTIONS
.TP
.I "\-c, \-\-cmd=[program]"
Execute the specified program, logging anything output to
stdout or stderr.
.TP
.I "\-e, \-\-event=[number]"
Logs that the specified event happened. Used in conjuction
with \fB\-\-name\fR. Currently specified events are:
.PD 0
.RS 8n
.TP 3n
.B 1
the action completed successfully
.TP
.B 2
the action failed
.TP
.B 3
the action was cancelled at user request
.TP
.B 4
the action failed due to the failure of a dependent action
.RE
.PD
.TP
.I "\-f, \-\-facility=[facility]"
Log at the specified syslog facility. The default
is \fBdaemon\fR (see syslog(3)).
.TP
.I "\-n, \-\-name=[string]"
Log the event under the specified string, such as
"inetd".
.TP
.I "\-p, \-\-priority=[priority]"
Log at the specified syslog priority. The default
is \fBnotice\fR (see syslog(3)).
.TP
.I "\-q"
Do not print the program's output, unless it exits
with a non-zero exit code.
.TP
.I "\-r, \-\-run=[program]"
Execute the specified program, with an open file
descriptor so that the program can pass back
commands to initlog.
.TP
.I "\-s, \-\-string=[string]"
Log the specified string to the logger.
.TP
.I "\-\-conf=[file]"
Specifies an alternate configuration file.
.SH FILES
.I /etc/initlog.conf
.SH "SEE ALSO"
syslog(3), logger(1)
