.TH IPCALC 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH NAME
ipcalc \- perform simple manipulation of ip addresses
.SH SYNOPSIS
.B ipcalc
\fI[--hostname] [--broadcast] [--network] \fBip \fI[netmask]\fR

.SH DESCRIPTION
\fBipcalc\fR provides a simple way to find the broadcast address, network
address, or hostname for a given IP address and netmask (no netmask is
needed if only the hostname is requested). The various options specify
what information \fBipcalc\fR should display on standard out. Multiple
options may be specified.

.SH OPTIONS
.TP
.IP \fI--broadcast\fR 
Display the broadcast address for the given ip address and netmask.

.IP \fI--hostname\fR 
Display the hostname for the given ip address.

.IP \fI--network\fR 
Display the network address for the given ip address and netmask.

.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
