.TH IPCALC 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH NAME
ipcalc \- perform simple manipulation of IP addresses
.SH SYNOPSIS
.B ipcalc
\fI[--hostname] [--broadcast] [--network] [--netmask] \fBip \fI[netmask]\fR

.SH DESCRIPTION
\fBipcalc\fR provides a simple way to calculate IP information for a host.
The various options specify what information \fBipcalc\fR should display
on standard out. Multiple options may be specified.

.SH OPTIONS
.TP
.IP \fI--broadcast\fR 
Display the broadcast address for the given IP address and netmask.

.IP \fI--hostname\fR 
Display the hostname for the given IP address.

.IP \fI--netmask\fR
Calculate the netmask for the given IP address. It assumes that the IP
address is in a complete Class A, B, or C network. Many networks do
not use the default netmasks, in which case an inappropriate value will
be returned.

.IP \fI--network\fR 
Display the network address for the given IP address and netmask.

.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
