.TH NETREPORT 1 "Red Hat, Inc." "RH" \" -*- nroff -*-
.SH NAME
netreport \- request notification of network interface changes
.SH SYNOPSIS
.B netreport
\fI[\fP-r\fI]\fP
.SH DESCRIPTION
.B netreport
tells the network management scripts to send a SIGIO signal
to the process which called netreport when any network interface
status changes occur.
.SH OPTIONS
.TP
.B -r
Remove the current request (if any) for the calling process.
.PP
.SH NOTES
If a program does not call netreport with the
.B -r
option before it exits, and another process is created with the
same PID before any changes take place in interface status, it
is possible that the new process will receive a spurious SIGIO.
