.TH PPP-WATCH 8 "Red Hat, Inc." "RHS" \" -*- nroff -*-
.SH NAME
ppp-watch \- daemon to make PPP interfaces act more like other interfaces
.SH SYNOPSIS
.B ppp-watch
\fIinterface-name\fP [boot]
.SH DESCRIPTION
.B ppp-watch
manages one PPP connection, including starting, stopping, and redialing.
It makes starting and stopping the connection synchronous activities.

.B ppp-watch
is not really meant to be called directly.  It should only be used from
within the ifup-ppp script.
.SH OPTIONS
.TP
.I interface-name
The name of the PPP interface to bring up.
.TP
boot
ppp-watch is being called at boot time and should time out after a
while if the PPP connection does not come up in order not to hang
the boot sequence.
