.\" A man page for rename_device(1). -*- nroff -*-
.\"
.\" Copyright (C) 2006 Red Hat, Inc. All rights reserved.
.\"
.\" This copyrighted material is made available to anyone wishing to use,
.\" modify, copy, or redistribute it subject to the terms and conditions of the
.\" GNU General Public License v.2.
.\"
.\" This program is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for 
.\" more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
.\"
.\" Author: Bill Nottingham <notting@redhat.com>
.TH rename_device 1 "Mar 2006"

.SH NAME
rename_device \- rename ethernet devices

.SH SYNOPSIS
\fBrename_device\fR

.SH DESCRIPTION
.B rename_device
renames ethernet devices, based on configuration in
\fI/etc/sysconfig/network-scripts\fR. It is meant to be run as a udev
helper; do not run it directly.

.SH FILES

\fI/etc/sysconfig/network-scripts\fR
.br
\fI/etc/udev/rules.d/60-net.rules\fR
.br

.SH BUGS
Probably, but let's hope not.  If you find any, please file them in the
bug database at http://bugzilla.redhat.com/ against the "initscripts"
component.
