.\" Copyright 2009 Petr Lautrbach (plautrba@redhat.com)
.TH securetty 8  2009-10-27 "" "System Administration tools and Daemons"
.SH NAME
securetty \- add a tty to /etc/securetty
.SH SYNOPSIS
.B securetty \fItty\fP
.SH DESCRIPTION
.B securetty
safely adds \fItty\fP to /etc/securetty.
.SH NOTES
.B securetty
is not normally meant to be run by hand; it is invoked by the upstart job that
sets up the system serial console.
.SH "SEE ALSO"
.BR securetty(5)
