.\" Copyright 2009 Petr Lautrbach (plautrba@redhat.com)
.TH setsysfont 8  2009-10-27 "" "System Administration tools and Daemons"
.SH NAME
setsysfont \- set console font according to /etc/sysconfig/i18n.
.SH SYNOPSIS
.B setsysfont
.SH DESCRIPTION
.B setsysfont
sets the console font for current virtual terminal. The font setting is read from /etc/sysconfig/i18n.
.SH NOTES
.B setsysfont
should not need to be called in normal practice, as the font is set on boot.

.SH FILES
.TP
\fB/etc/sysconfig/i18n\fR

.SH "SEE ALSO"
.BR /usr/share/doc/initscripts-*/sysconfig.txt,
.BR unicode_start (1),
.BR setfont (8),
.BR consoletype (1)
