.TH SUSHELL 8 "Red Hat, Inc" \" -*- nroff -*-
.SH NAME
sushell \- execute the single-user shell
.SH SYNOPSIS
.B sushell
.SH DESCRIPTION
.B sushell
executes the single-user shell. By default, this is
\fI/bin/bash\fP
This can be configured via the
.B SUSHELL
environment variable.
.SH NOTES
.B sushell
is an implementation detail, required for proper SELinux
usage. It is not intended to be run regularly.
