.TH USERNETCTL 1 "Red Hat Software" "RHS" \" -*- nroff -*-
.SH NAME
usernetctl \- allow a user to manipulate a network interface if permitted
.SH SYNOPSIS
.B usernetctl
\fIconfig-file-name\fP up\fI|\fPdown
.SH DESCRIPTION
.B usernetctl
checks to see if users are allowed to manipulate the network interface
specified by \fIconfig-file-name\fP, and then tries to bring the network
interface up or down, as specified.
.SH OPTIONS
.TP
.I "\fIconfig-file-name"
The name of the network configuration file to read; for example, ifcfg-ppp0
.TP
up\fI|\fPdown
Attempt to bring the interface up or down.
.SH NOTES
Alternate device configurations may inherit the default configuration's
permissions.
