name: Differential ShellCheck
on:
  pull_request:
    branches: [ main, rhel*-branch ]

jobs:
  shellCheck:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
