name: Differential ShellCheck
on:
  pull_request:
    branches: [ master, rhel*-branch ]

jobs:
  shellCheck:
    runs-on: ubuntu-20.04

    steps:    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v2
        with:
          ignored-codes: .github/.diff-shellcheck-exceptions.txt
          shell-scripts: .github/.diff.shellcheck-scripts.txt
          token: ${{ secrets.GITHUB_TOKEN }}
