# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Shellcheck test
on:
  pull_request:
    branches:
      - master
      - rhel*-branch

jobs:
  shellCheck:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install -y cmake help2man libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev tree
      - name: Clone csdiff repository
        run: cd ../ && git clone --depth=1 https://github.com/kdudka/csdiff.git && cd -
      - name: Build and install csdiff
        run: cd ../csdiff && sudo make && sudo make install && cd -
      - name: Repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}  
      - name: Run shell-check test
        run: bash ./.github/workflows/check-shell.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
