name: Differential ShellCheck
on:
  pull_request:
    branches: [ master, rhel*-branch ]

jobs:
  shellCheck:
    runs-on: ubuntu-20.04

    steps:    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v2
        with:
          github-token: ${{ secrets.GA_WORKFLOW_TOKEN }}
          # Colored GH comments: https://stackoverflow.com/a/39413824
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '```diff\n@@ Shellcheck test summary @@\n- added issues: ${{ env.NUMBER_OF_ADDED_ISSUES }}\n+ solved issues: ${{ env.NUMBER_OF_SOLVED_ISSUES }}\n\n# list of edited shell scripts:\n${{ env.LIST_OF_SCRIPTS }}\n```'
            })

      # TODO: Set labels based on env.NUMBER_OF_ADDED_ISSUES and env.NUMBER_OF_SOLVED_ISSUES
